### ISSUE TITLE
A tool with more features

### ISSUE THREAD

**Issue by ndkoval** [TOPdesk/time-transformer-agent#1]
Hi,
Maybe you will be interested in my tool, which instruments not `System.currentTimeMillis()` and `System.nanoTime()` methods, but other time-dependent methods as well.
<https://github.com/Devexperts/time-test>

**Comment by JoepWeijers** [comment]
Nice to see you published the tool you talked to me about at Devoxx Nikita! But I'm closing this issue as this is not an issue with the time-transformer-agent.
